import { openDb, createSchema } from './db.js';

const db=openDb(); createSchema(db); const today=new Date().toISOString().slice(0,10);
const users=db.prepare("SELECT id,emp_no,name,role,scope,unit_id FROM users WHERE status='在岗'").all();
const byName=new Map(users.map(x=>[x.name,x]));
const fallback=(role,unit,scope)=>users.find(x=>x.role===role&&(!unit||x.unit_id===unit)&&(!scope||x.scope===scope));
function assign(p,title,initiator){const t=JSON.parse(p?.team_json||'{}');let n='';if(/项目负责人/.test(title))n=t.owner;else if(/一级总师/.test(title))n=t.chief1;else if(/二级|三级.*总师|责任总师|学术委员会|专委会/.test(title))n=t.chief2||t.chief1;else if(/财务/.test(title))n=/总部/.test(title)?t.finHq:t.finHead||t.finStaff;else if(/总部|科研项目处|科技发展处|科技管理部|理事会/.test(title))n=t.hqHead||t.hqStaff;else if(/单位|承担部门/.test(title))n=t.unitDeptHead||t.unitStaff;else if(/联系人|团队|项目组/.test(title))n=initiator||t.owner;let u=byName.get(n);if(!u&&/总师|委员会|理事会/.test(title))u=fallback('chief');if(!u&&/财务/.test(title))u=/总部/.test(title)?fallback('mgmt',null,'hq'):fallback('finance',p?.lead_unit_id);if(!u&&/总部|科研项目处|科技发展处|科技管理部/.test(title))u=fallback('mgmt',null,'hq');if(!u&&/单位|承担部门/.test(title))u=fallback('mgmt',p?.lead_unit_id);if(!u&&/项目|联系人|团队/.test(title))u=fallback('team',p?.lead_unit_id);return u?{assignee:u.name,assigneeId:u.emp_no||u.id}:null;}
let approvals=0;
for(const a of db.prepare("SELECT * FROM approvals WHERE status='审批中'").all()){const p=a.project_id?db.prepare('SELECT * FROM projects WHERE id=?').get(a.project_id):null;const steps=JSON.parse(a.steps_json||'[]');let changed=false;for(const s of steps){if(!s.assignee||!s.assigneeId){const exact=byName.get(s.assignee);const x=exact?{assignee:exact.name,assigneeId:exact.emp_no||exact.id}:assign(p,s.title,a.initiator);if(x){Object.assign(s,x);changed=true;}}}if(changed){db.prepare('UPDATE approvals SET steps_json=? WHERE id=?').run(JSON.stringify(steps),a.id);approvals++;}}
let finance=0;
for(const p of db.prepare('SELECT * FROM projects').all()){if(!db.prepare('SELECT 1 FROM project_finance_profile WHERE project_id=?').get(p.id)){db.prepare("INSERT INTO project_finance_profile (project_id,central_grant,internal_grant,self_fund,internal_self_fund,source) VALUES (?,0,0,0,0,'待治理')").run(p.id);finance++;}}
let quality=0;const ins=db.prepare("INSERT OR IGNORE INTO data_quality_issues (project_id,issue_code,detail,status,detected_at) VALUES (?,?,?,'待治理',?)");for(const p of db.prepare('SELECT * FROM projects').all()){if(!p.goal){quality+=ins.run(p.id,'MISSING_GOAL','项目目标为空',today).changes;}if(!db.prepare('SELECT 1 FROM milestones WHERE project_id=?').get(p.id)){quality+=ins.run(p.id,'NO_MILESTONE','未建立里程碑',today).changes;}if(!db.prepare('SELECT 1 FROM deliverables WHERE project_id=?').get(p.id)){quality+=ins.run(p.id,'NO_DELIVERABLE','未建立交付物',today).changes;}}
console.log(JSON.stringify({approvalAssignmentsUpdated:approvals,financeProfilesCreated:finance,dataQualityIssuesCreated:quality}));
